apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    name: nodejs-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      name: http
      protocol: TCP
  selector:
    name: nodejs
