apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-service
  name: rest-service
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: rest-service

