spring:
  profiles:
    active: local,master
  application:
    name: UploaderJobTask
  #batch:
    #initialize-schema: always
  cloud:
    task:
      # Not available yet
      #closecontext:
      #  enabled: true
      closecontextEnabled: true

batch:
  incrementerEnabled: true
  failurePercentage: 0
  max-threads: 1
  max-workers: 1

logging:
  level:
    root: INFO
    org.springframework.cloud.task: DEBUG
    org.springframework.web: INFO
    com.example: DEBUG

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://dockerhost:5432/dataflow
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

batch:
  max-threads: 2
  max-workers: 2
  worker-app: maven://com.example:batch-uploader-k8s:0.0.1-SNAPSHOT
  storage:
    url: http://dockerhost:9000
    accessKey: minio
    secretKey: password

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/dataflow
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

batch:
  max-threads: 4
  max-workers: 1
  worker-app: maven://com.example:batch-uploader-k8s:0.0.1-SNAPSHOT
  storage:
    url: http://minio:9000
    accessKey: minio
    secretKey: password

---
spring:
  profiles: k8s
  datasource:
    url: jdbc:postgresql://postgres.default.svc.cluster.local:5432/dataflow
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

batch:
  max-threads: 2
  max-workers: 2
  worker-app: docker:jsa4000/dataflow-batch-uploader-k8s:0.0.1-SNAPSHOT
  storage:
    url: http://minio.default.svc.cluster.local:9000
    accessKey: minio
    secretKey: password