spring:
  profiles:
    active: local
  application:
    name: kafka-consumer
  data.mongodb:
    database: consumer-view
  kafka:
    offset-reset: latest
    auto-commit: false

management:
  endpoints:
    web.exposure.include: health,beans,env

application:
  topic:
    roles: roleManagement
    users: userManagement

---
spring:
  profiles: local
  kafka:
    bootstrap-servers: http://dockerhost:9092
  data.mongodb:
    uri: mongodb://root:root@dockerhost:27017/admin

server:
  port: 8081

management:
  server.port: 9501

---
spring:
  profiles: docker
  kafka:
    bootstrap-servers: http://kafka:9092
  data.mongodb:
    uri: mongodb://root:root@mongodb:27017/admin

server:
  port: 8080

management:
  server.port: 9500
