spring:
  profiles:
    active: local
  application:
    name: kafka-consumer
  data.mongodb:
    database: database
  kafka:
    offset-reset: latest
    auto-commit: false

management:
  endpoints:
    web.exposure.include: health,beans,env

application:
  topic:
    roles: roleManagement
    users: userManagement

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.example: DEBUG

tracing:
  #provider: JAEGER
   provider: ZIPKIN

---
spring:
  profiles: local
  kafka:
    bootstrap-servers: http://dockerhost:9092
  data.mongodb:
    uri: mongodb://root:root@dockerhost:27017/admin

server:
  port: 8081

management:
  server.port: 9501

tracing:
  provider:
    zipkin.url: http://dockerhost:9412/api/v2/spans
    jaeger:
      host: dockerhost
      port: 6831

---
spring:
  profiles: docker
  kafka:
    bootstrap-servers: http://kafka:9092
  data.mongodb:
    uri: mongodb://root:root@mongodb:27017/admin

server:
  port: 8080

management:
  server.port: 9500

tracing:
  provider:
    zipkin.url: http://zipkin:9412/api/v2/spans
    jaeger:
      host: jaeger
      port: 6831