apiVersion: v1
kind: Secret
metadata:
  name: {{ template "scdf.fullname" . }}
  labels:
    app: {{ template "scdf.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  database-password: {{ .Values.datasource.password | b64enc | quote }}
