{{- if .Values.server.ingress.enabled -}}
{{- $fullName := include "scdf.fullname" . -}}
{{- $servicePort := .Values.server.service.externalPort -}}
{{- $ingressPath := .Values.server.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-server
  labels:
    app: {{ template "scdf.name" . }}
    component: server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.server.ingress.labels }}
{{ toYaml .Values.server.ingress.labels | indent 4 }}
{{- end }}
{{- with .Values.server.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.server.ingress.tls }}
  tls:
  {{- range .Values.server.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.server.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-server
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}