spring:
  profiles:
    active: local,master
  application:
    name: batchJobTaskProd
  #batch:
    #initialize-schema: always
  cloud:
    task:
      # Not available yet
      #closecontext:
      #  enabled: true
      closecontextEnabled: true

batch:
  max-threads: 1
  max-workers: 1
  inputFile: dataflow-bucket:sample-data-prod.zip
  resourcesPath: dataflow-bucket/sample-data-prod
  tempPath: /tmp/data
  filePattern: "*.csv"

logging:
  level:
    root: INFO
    org.springframework.cloud.task: DEBUG
    org.springframework.web: INFO
    com.example: DEBUG

management:
  endpoints:
    web.exposure.include: health,beans,env,info

---
spring:
  profiles: local

batch:
  max-threads: 2
  max-workers: 2
  departmentsUri: http://dockerhost:8080/departments
  worker-app: maven://com.example:batch-process-prod-k8s:0.0.1-SNAPSHOT
  datasource:
    first:
      url: jdbc:postgresql://dockerhost:5432/dataflow
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
    second:
      url: jdbc:postgresql://dockerhost:5432/db
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
  storage:
    url: http://dockerhost:9000
    accessKey: minio
    secretKey: password

---
spring:
  profiles: docker

batch:
  max-threads: 4
  max-workers: 1
  departmentsUri: http://rest-service:8080/departments
  worker-app: docker:jsa4000/dataflow-batch-process-prod-k8s:0.0.1-SNAPSHOT
  datasource:
    first:
      url: jdbc:postgresql://postgres:5432/dataflow
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
    second:
      url: jdbc:postgresql://postgres:5432/db
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
  storage:
    url: http://minio:9000
    accessKey: minio
    secretKey: password

---
spring:
  profiles: k8s

batch:
  max-threads: 2
  max-workers: 2
  departmentsUri: http://rest-service.default.svc.cluster.local:8080/departments
  worker-app: docker:jsa4000/dataflow-batch-process-prod-k8s:0.0.1-SNAPSHOT
  datasource:
    first:
      url: jdbc:postgresql://postgres.default.svc.cluster.local:5432/dataflow
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
    second:
      url: jdbc:postgresql://postgres.default.svc.cluster.local:5432/db
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
  storage:
    url: http://minio.default.svc.cluster.local:9000
    accessKey: minio
    secretKey: password