apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          applicationProperties:
            stream:
              management:
                metrics:
                  export:
                    prometheus:
                      enabled: true
                endpoints:
                  web:
                    exposure:
                      include: 'prometheus,info,health'

          grafana-info:
            url: 'http://grafana:3000'
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    livenessProbeDelay: 90
                    livenessProbePeriod: 90
                    limits:
                      memory: 1024Mi
                      #cpu: 500m
      datasource:
        url: jdbc:postgresql://postgres.default.svc.cluster.local:5432/dataflow
        username: postgres
        password: password
        driverClassName: org.postgresql.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"

