apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanup-jobs
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kubectl-runner
              image: wernight/kubectl
              command: ["sh", "-c", "kubectl get jobs | awk '$4 ~ /[2-9]d$/ || $3 ~ 1' | awk '{print $1}' | xargs kubectl delete job"]
          restartPolicy: Never