# prometheus.yml

global:
  scrape_interval:     1s 
  evaluation_interval: 1s 
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
     - targets: ['localhost:9090']

  - job_name: 'nodeexporter'
    static_configs:
     - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    static_configs:
     - targets: ['cadvisor:8080']
     
  - job_name: 'kafkaexporter'
    static_configs:
     - targets: ['10.0.0.12:7071']