spring:
  application:
    name: batchJobTask
  batch:
    #job.enabled: false
    initialize-schema: always
  #jpa.database: default
  #jpa.hibernate.ddl-auto: update

batch:
  max-threads: 4
  filename: C:/test/sample-data.zip
  tempDir: C:/test/data
  pattern: C:/test/data/*.csv
  departmentsUri: http://localhost:8081/departments
  worker-app: C:/Users/jsantosa/.m2/repository/com/example/batch-process/0.0.1-SNAPSHOT/batch-process-0.0.1-SNAPSHOT.jar
  datasource:
    first:
      initialization-mode: always
      url: jdbc:mysql://dockerhost:3306/db
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    second:
      initialization-mode: always
      url: jdbc:postgresql://dockerhost:5432/db
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
