spring:
  profiles:
    active: local
  application:
    name: scdf-orchestrator
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      generate-ddl: false
      ddl-auto: none
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  cloud:
    task:
      initialize:
        enable: false

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /management
      exposure.include: health,beans,env,info

orchestrator:
  maxWaitTime: 60

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example: DEBUG

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://dockerhost:5432/oschestrator
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

orchestrator:
  dataflowServerUri: http://dockerhost:9393

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/oschestrator
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

orchestrator:
  dataflowServerUri: http://dataflow-server:9393

---
spring:
  profiles: k8s
  datasource:
    url: jdbc:postgresql://postgres.default.svc.cluster.local:5432/oschestrator
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

orchestrator:
  dataflowServerUri: http://dataflow-server.default.svc.cluster.local:9393