server:
  port: 8080

spring:
  application:
    name: batchJob
  batch:
    job.enabled: false
    initialize-schema: always
  #jpa.database: default
  #jpa.hibernate.ddl-auto: update
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://dockerhost:5432/db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

batch:
  max-threads: 4
  filename: sample-data.zip
  tempDir: src/main/resources/data
  pattern: src/main/resources/data/*.csv
  departmentsUri: http://localhost:8081/departments
  worker-app: D:/Minsait/Projects/Github/Getting-Started-Microservices/pipelines/batch/src/04-batch-tasks/batch-process/build/libs/batch-process-0.0.1-SNAPSHOT.jar

