# prometheus.yml

global:
  scrape_interval:     5s 
  evaluation_interval: 5s 
  external_labels:
    monitor: 'my-monitor'

rule_files:
  - "alert.rules"
  - "kafka.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
     - targets: ['localhost:9090']
     
  - job_name: 'overwritten-default'

    consul_sd_configs:
    - server: 'consul-server:8500'
      services: ['cadvisor', 'nodeexporter', 'kafkaexporter1','kafkaexporter2','kafkaexporter3']

    relabel_configs:
        - source_labels: ['__meta_consul_service']
          regex:         '(.*)'
          target_label:  'job'
          replacement:   '$1'
        - source_labels: ['__meta_consul_service_address']
          regex:         '(.*)'
          target_label:  'instance'
          replacement:   '$1'
        - source_labels: ['__meta_consul_service_address', '__meta_consul_service_port']
          regex:         '(.*);(.*)'
          target_label:  '__address__'
          replacement:   '$1:$2'
        - source_labels: ['__meta_consul_tags']
          regex:         ',(production|canary),'
          target_label:  'group'
          replacement: '$1'