apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_SECRET_KEY
          value: password
        image: minio/minio:RELEASE.2019-03-27T22-35-21Z
        name: minio
        resources: {}
      restartPolicy: Always
