apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: rest-service
  name: rest-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-service
    spec:
      containers:
      - image: jsa4000/dataflow-rest-service
        name: rest-service
        resources: {}
      restartPolicy: Always

