---
- name: Installing common packages and updates
  hosts: node
  remote_user: vagrant
  become: yes
  tasks:
  - name: Run apt-get update
    apt: update_cache=yes

  - name: Update all packages to the latest version
    apt: upgrade=dist

  - name: Install Standard Packages
    apt:
      pkg:
        - vim
        - git
        - curl
        - htop
      state: present
   