management:
  endpoints:
    web.exposure.include: health,beans,env

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    com.example: DEBUG
    com.netflix.loadbalancer.LoadBalancerContext: DEBUG

zuul:
  ignoredServices: "*"
  retryable: true
  ribbon-isolation-strategy: thread
  threadPool:
      useSeparateThreadPools: true
  routes:
    customer:
      retryable: true
      serviceId: customer
      path: /customer/**

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
    customer:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

customer:
  ribbon:
    enabled: true
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100

---
spring:
  profiles: local

server:
  port: 8080

management:
  server.port: 9500

zuul:
  routes:
    customer:
      url: http://localhost:8081

---
spring:
  profiles: docker

server:
  port: 8080

management:
  server.port: 9500

zuul:
  routes:
    customer:
      url: http://customer:8080
