management:
  endpoints:
    web.exposure.include: health,beans,env

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.example: DEBUG

---
spring:
  profiles: local

server:
  port: 8080

management:
  server.port: 9500

zuul:
  routes:
    customer:
      path: /customer/**
      url: http://localhost:8081

---
spring:
  profiles: docker


server:
  port: 8080

management:
  server.port: 9500

zuul:
  routes:
    customer:
      path: /customer/**
      url: http://customer:8081
