spring:
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web.exposure.include: health,beans,env,info

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.example: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

zuul:
  ignoredServices: "*"
  prefix: /api
  host:
    max-total-connections: 1000
    max-per-route-connections: 100
  semaphore:
    max-semaphores: 500
  routes:
    customer:
      serviceId: customer
      path: /customer/**

ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 990000
  maxAutoRetries: 2
  MaxAutoRetriesNextServer: 2

server:
  port: 8080

---
spring:
  profiles: local
  zipkin:
    enabled: false
    locator:
      discovery:
        enabled: false

zuul:
  routes:
    customer:
      url: http://localhost:8081
---
spring:
  profiles: docker
  zipkin:
    base-url: http://zipkin:9411
    enabled: true
    locator:
      discovery:
        enabled: true

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024


