spring:
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web.exposure.include: health,beans,env,info

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.example: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

security:
  enabled: true
  symmetricKey: as466gf
  resourceId: application
  accessTokenValidity: 3600
  refreshTokenValidity: 21600
  authorities:
    basic:
      name: basic-client
      secret: password
    normal:
      name: normal-client
      secret: password
    trusted:
      name: trusted-client
      secret: password

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignoreSecurityHeaders: false
  ignoredServices: "*"
  prefix: /api
  host:
    max-total-connections: 1000
    max-per-route-connections: 100
  semaphore:
    max-semaphores: 500
  routes:
    customer:
      serviceId: customer
      path: /customer/**
    catalog:
      serviceId: catalog
      path: /catalog/**
    management:
      serviceId: management
      path: /management/**

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
  maxAutoRetries: 2
  MaxAutoRetriesNextServer: 2

server:
  port: 8080
  error.whitelabel.enabled: false
---
spring:
  profiles: local
  zipkin:
    enabled: false
    locator:
      discovery:
        enabled: false

zuul:
  routes:
    customer:
      url: http://localhost:8081
    catalog:
      url: http://localhost:8082
    management:
      url: http://localhost:8083

management:
  ribbon:
    listOfServers: localhost:8083

---
spring:
  profiles: docker
  zipkin:
    base-url: http://zipkin:9411
    enabled: true
    locator:
      discovery:
        enabled: true

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
    min-response-size: 1024


