management:
  endpoints:
    web.exposure.include: health,beans,env,info

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    com.example: DEBUG

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    customer:
      serviceId: customer
      path: /customer/**
  ribbon:
    customer:
      enabled: true

ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 990000
  maxAutoRetries: 2
  MaxAutoRetriesNextServer: 2

server:
  port: 8080
---
spring:
  profiles: local

zuul:
  routes:
    customer:
      url: http://localhost:8081
---
spring:
  profiles: docker



