management:
  endpoints:
    web.exposure.include: health,beans,env,info

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.example: DEBUG

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    customer:
      retryable: true
      serviceId: customer
      path: /customer/**
    customer-management:
      retryable: true
      serviceId: customer-management
      path: /customer-management/**

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

---
spring:
  profiles: local

server:
  port: 8080

zuul:
  routes:
    customer:
      url: http://localhost:8081
    customer-management:
      url: http://localhost:9501/actuator

---
spring:
  profiles: docker

server:
  port: 8080

zuul:
  routes:
    customer:
      #url: http://customer
    customer-management:
      #url: http://customer-management/actuator