kind: Service
apiVersion: v1
metadata:
  name: {{ template "batch.fullname" . }}-rest-service
  labels:
    app: {{ template "batch.name" . }}
    component: rest-service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  # If you are running k8s on a local dev box, you can use type NodePort instead
  type: {{ .Values.restService.service.type }}
  ports:
    - port: {{ .Values.restService.service.externalPort }}
      targetPort: http
      name: http
  selector:
    app: {{ template "batch.name" . }}
    component: rest-service
    release: {{ .Release.Name }}
