version: '2'

networks:
  mynetwork:
    driver: bridge  

services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - mynetwork
    ports:
      - "2181:2181"
      
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    depends_on:
     - zookeeper
    networks:
      - mynetwork
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.10
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  
   
