version: '3'

volumes:
    prometheus_data: 
    grafana_data:

networks:
  mynetwork:
    driver: bridge  
    
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - mynetwork
    volumes:
      - /vagrant/deployments/Prometheus/prometheus-lite.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - '9090:9090'
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - mynetwork
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - '3000:3000'
    labels:
      org.label-schema.group: "monitoring"
     
 


