apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: db-migration
  name: db-migration
spec:
  template:
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
          value: org.postgresql.Driver
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres.default.svc.cluster.local:5432/db
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        image: jsa4000/dataflow-db-migration
        name: db-migration
        resources: {}
      initContainers:
      # Create databases if not exists. This initialization is specific only on postgres databases.
      # Use 'jdbc:mysql://dbhost:5432/db?createDatabaseIfNotExist=true' for other databases that supports this feature
      - name: init-crecate-db
        image: postgres:10.7-alpine
        command: ['sh', '-c', 'PGPASSWORD=password createuser -h postgres.default.svc.cluster.local -p 5432 -U postgres db; PGPASSWORD=password createdb -h postgres.default.svc.cluster.local -p 5432 -O db -U postgres db;echo 0']
      - name: init-create-dataflow
        image: postgres:10.7-alpine
        command: ['sh', '-c', 'PGPASSWORD=password createuser -h postgres.default.svc.cluster.local -p 5432 -U postgres dataflow; PGPASSWORD=password createdb -h postgres.default.svc.cluster.local -p 5432 -O dataflow -U postgres dataflow;echo 0']
      restartPolicy: Never

