apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: createbuckets
  name: createbuckets
spec:
  template:
      containers:
      - command:
        - /bin/sh
        - -c
        - ' while ! nc -z minio 9000; do echo ''Wait minio to startup...''; sleep 0.1; done;
          sleep 5;
          /usr/bin/mc config host add data http://minio.default.svc.cluster.local:9000 minio password;
          /usr/bin/mc rm -r --force data/dataflow-bucket;
          /usr/bin/mc mb data/dataflow-bucket;
          /usr/bin/mc policy download data/dataflow-bucket;
          ls -la /sample-data;
          /usr/bin/mc cp /sample-data/sample-data.zip data/dataflow-bucket;
          exit 0; '
        image: minio/mc
        name: createbuckets
        resources: {}
      restartPolicy: Never


