apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: db-migration
  name: db-migration
spec:
  template:
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
          value: org.postgresql.Driver
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres.default.svc.cluster.local:5432/db
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        image: jsa4000/dataflow-db-migration
        name: db-migration
        resources: {}
      restartPolicy: Never

