spring:
  data.mongodb:
    database: customer

management:
  endpoints:
    web.exposure.include: health,beans,env,info

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.example: DEBUG

---
spring:
  profiles: local
  data.mongodb:
    uri: mongodb://root:root@localhost:27017/admin

server:
  port: 8081

management:
  server.port: 9501

---
spring:
  profiles: docker
  data.mongodb:
    uri: mongodb://root:root@mongodb:27017/admin

server:
  port: 8080

management:
  server.port: 9500
