version: '2'

networks:
  mynetwork:
    driver: bridge  

services:

  zookeeper1:
    image: confluentinc/cp-zookeeper:3.3.0
    networks:
      - mynetwork
    ports:
      - "22181:22181"
      - "22888:22888"
      - "23888:23888"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888
      
  zookeeper2:
    image: confluentinc/cp-zookeeper:3.3.0
    depends_on:
    - zookeeper1
    networks:
      - mynetwork
    ports:
      - "32181:32181"
      - "32888:32888"
      - "33888:33888"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888
   
  zookeeper3:
    image: confluentinc/cp-zookeeper:3.3.0
    depends_on:
      - zookeeper1
      - zookeeper2
    networks:
      - mynetwork
    ports:
      - "42181:42181"
      - "42888:42888"
      - "43888:43888"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888
   
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - mynetwork
    ports:
      - "9092:9092"
      - "9992:9992"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: 1
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=10.0.0.11 -Dcom.sun.management.jmxremote.rmi.port=9992"
      JMX_PORT: 9992
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.11
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafkaexporter:
    image: sscaling/jmx-prometheus-exporter
    container_name: kafkaexporter
    networks:
      - mynetwork
    ports: 
      - "7071:7071" 
    depends_on:
      - kafka
    volumes:
      - /vagrant/deployments/prom-jmx-exporter-config.yml:/opt/jmx_exporter/config.yml
    environment:
      SERVICE_PORT: 7071

 