apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins-instance
spec:
  master:
    securityContext:
      fsGroup: 1000
      runAsUser: 1000
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 30
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 2048
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 30
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 2048
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git