nexusProxy:
  enabled: false

persistence:
  storageSize: 5Gi

service:
  enabled: true
  ports:
  - name: nexus-service
    targetPort: 8081
    port: 8081
  - name: nexus-registry
    targetPort: 5003
    port: 5003

resources:
  requests:
    cpu: 250m
    memory: 1Gi