apiVersion: apps.m88i.io/v1alpha1
kind: Nexus
metadata:
  name: nexus3
spec:
  networking:
    expose: true
    exposeAs: Ingress
    host: nexus.cicd.com
  persistence:
    persistent: true
    volumeSize: 5Gi
  replicas: 1
  resources:
    limits:
      cpu: '2'
      memory: 2Gi
    requests:
      cpu: '1'
      memory: 2Gi
  useRedHatImage: false
