spring:
  profiles:
    active: local
  application:
    name: kafka-producer
  kafka:
    acks: all
    compression.type: gzip
    enable.idempotence: true
    batch.size: 16384
    linger.ms: 500
    max.in.flight.requests.per.connection: 1
    retries: 1

management:
  endpoints:
    web.exposure.include: health,beans,env

application:
  topic:
    roles: roleManagement
    users: userManagement

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.example: DEBUG

tracing:
  provider: JAEGER

---
spring:
  profiles: local
  kafka:
    bootstrap-servers: http://dockerhost:9092

server:
  port: 8080

management:
  server.port: 9500

tracing:
  provider:
    zipkin.url: http://dockerhost:9412/api/v2/spans
    jaeger:
      host: dockerhost
      port: 6831

---
spring:
  profiles: docker
  kafka:
    bootstrap-servers: http://kafka:9092

server:
  port: 8080

management:
  server.port: 9500

tracing:
  provider:
    zipkin.url: http://zipkin:9412/api/v2/spans
    jaeger:
      host: jaeger
      port: 6831