spring:
  profiles:
    active: local
  application:
    name: kafka-producer

management:
  endpoints:
    web.exposure.include: health,beans,env

---
spring:
  profiles: local

server:
  port: 8080

management:
  server.port: 9500

---
spring:
  profiles: docker

server:
  port: 8080

management:
  server.port: 9500
