server:
  port: 8080

spring:
  batch:
    job.enabled: false
    initialize-schema: always
  #jpa.database: default
  #jpa.hibernate.ddl-auto: update

batch:
  max-threads: 4
  filename: sample-data.csv
  departmentsUri: http://localhost:8081/departments
  datasource:
    first:
      initialization-mode: always
      url: jdbc:mysql://dockerhost:3306/db
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    second:
      initialization-mode: always
      url: jdbc:postgresql://dockerhost:5432/db
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver