# prometheus.yml

global:
  scrape_interval:     5s 
  evaluation_interval: 5s 
  external_labels:
    monitor: 'my-monitor'

rule_files:
  #- "alert.rules"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
     - targets: ['localhost:9090']

  - job_name: 'nodeexporter'
    static_configs:
     - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    static_configs:
     - targets: ['cadvisor:8080']
     
  - job_name: 'server-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
     - targets: ['server-gateway:9500']