version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
      
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    - "9992:9992"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: dockerhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  mongo:
    image: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root   
      
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
    - 9412:9411

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 16686:16686
    - 14268:14268
    - 9411:9411