spring:
  data.mongodb:
    database: catalog
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web.exposure.include: health,beans,env,info

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.example: DEBUG
---
spring:
  profiles: local
  data.mongodb:
    uri: mongodb://root:root@dockerhost:27017/admin
  zipkin:
    enabled: false
    locator:
      discovery:
        enabled: false

server:
  port: 8082
---
spring:
  profiles: docker
  data.mongodb:
    uri: mongodb://root:root@mongodb:27017/admin
  zipkin:
    base-url: http://zipkin:9411
    enabled: true
    locator:
      discovery:
        enabled: true
server:
  port: 8080
